### ISSUE TITLE
Add avatar image upload and update endpoint

### ISSUE THREAD

**Issue by jgwerner** [3Blades/openapi#62]
Document endpoint to upload and update user's avatar image.

3blades/3blades#84

**Comment by johngriebel** [comment]
@jgwerner Has this been done yet?

**Comment by jgwerner** [comment]
@johngriebel right now it is a part of the Swagger definition, however, I'm not sure if it has been defined correctly. The avatar url is a User --> Profile attribute.

```
  UserProfile:
    type: object
    properties:
      avatar_url:
        type: string
        description: "URL where user's avatar is located."
```
